# Alone1 Plugin by Alone

# name = Name des Projektes
# NormalTime = Sekunden auf dem Server sein | normal: 20min
# SchutzTime = Zeit der Schutzzeit (Es werden immer +5 Sek. gerechnet)
# FriendlyFire = Ob man den Teamkollegen schlagen darf
# defaultWorldborder.groesse = Die grösse der Worldborder am Anfang
# defaultWorldborder.schrumpfen = Wie viel die Grösse der Worldborder pro Tod eines Spielers verkleinert wird.
# Wieviele = Wie viele Spielen waren auf dem Server | Nicht aendern!
# high = Diese Zahl traegt dazu bei, dass das Plugin ueberhaupt funktioniert... | Also NICHT AENDERN!
# startWorldborderLoop = kann der Loop gestartet werden?? | Nicht aendern!
# Worldborder = Wie viel wird die Border nach hinten verschoben | Nicht aendern!
# start = Hat das Spiel schon begonnen?| Nicht aendern!
# team = Wie viele Teams gibt es | Nicht aendern!
# build = Wurde bereits eine Spawn Plattform gebaut? | Nicht aendern!
# Mitte = Zentum | Nicht aendern!
# Player[Zahl] = Viele wichtige Informationen zu den Spielern | Nicht aendern!
# team[Zahl] = Wichtige Informationen zu den Teams | Nicht aendern!

name: VARO
NormalTime: 1200
SchutzTime: 55
FriendlyFire: 0
defaultWorldborder.groesse: 1000
defaultWorldborder.schrumpfen: 75
WieViele: 0
high: 0
startWorldborderLoop: 1
Worldborder: 0
start: 0
team: 0
build: 0
Mitte.X: 0
Mitte.Y: 0
Mitte.Z: 0