# Alone1 Plugin by Alone

# name = Name des Projektes | normal: VARO
# NormalTime = Sekunden auf dem Server sein | normal: 1200 (20 Minuten)
# SchutzTime = Zeit der Schutzzeit (Es werden immer +5 Sek. gerechnet, da man sonst in diesen 5 Sek sterben würde[Fallschaden]) | normal = 55 (+5 Sek = 1 Minute)
# FriendlyFire = Ob man den Teamkollegen schlagen darf (0 = Nein | 1 = Ja) | normal: 0
# defaultWorldborder.groesse = Die Groesse der Worldborder am Anfang (in Blöcken gemessen) | normal: 1000
# defaultWorldborder.schrumpfen = Um wie viel Blöcke sich die Groesse der Worldborder pro Tod eines Spielers verkleinert. | normal: 75
# noKickZone = Wenn ein gegnerischer Spieler in deisem Umkreis ist, kann man nicht gekickt werden. | normal: 50

name: VARO
NormalTime: 1200
SchutzTime: 55
FriendlyFire: 0
defaultWorldborder.groesse: 1000
defaultWorldborder.schrumpfen: 75
noKickZone: 50