main: net.BundR.plugin1.plugin1
version: 1.0.3
name: alone1
author: Alone
website: http://www.BundR.net

commands:
  build:
    description: Spawn wird bei dir erschaffen
  zeit:
    description: Zeigt an wie lange man noch auf dem Server sein darf
  start:
    description: Startet alles
  alive:
    description: Zeigt an wer alles noch am Leben ist
  team:
    description: Command um den Team Kollegen zu bestimmen. /team [Spieler]
  teams:
    description: Liste der Teams
  BR:
    description: Ein geheimer Command